---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: awscli
spec:
  selector:
    matchLabels:
      name: awscli
  replicas: 1
  template:
    metadata:
      labels:
        app: awscli
    spec:
      #serviceAccountName: awscli
      restartPolicy: Always
      containers:
        - name: cli
          image: ingshtrom/awscli:latest
          imagePullPolicy: Always

